### PR TITLE
Empty array for non-existent tables

### PR DESCRIPTION
**Pull request by FenrirUnbound**
Starting up the API assumes that the save file always exist. If a developer is using a blank config file (e.g., only contains `{}` as its contents), it causes errors during scan operations. 

This PR is to reduce the restriction on the scan operation by allowing the user to scan against a table that doesn't exist yet. It will return an empty array instead of throw an error.

### CODE REVIEW

**Comment by d2lam** [comment]
Why do we want to do this? If the table doesn't exist, I would expect to get an error. It should follow what is expected in the datastore-base documentation: https://github.com/screwdriver-cd/datastore-base#scan

**Comment by stjohnjohnson** [comment]
@d2lam then should we be using `dynamic-datastore` to setup the IMDB?

**Comment by d2lam** [comment]
@stjohnjohnson  or something equivalent. I don't think it's a good idea changing the expected behavior of `scan` since it should be the same as `dynamodb` and should follow what `base` describes.

**Comment by petey** [comment]
👎  Like Dao said, this violates the contract of datastore-base.

**Comment by FenrirUnbound** [comment]
It's the expectation that the tables should exist in DynamoDB. This is done by the `dynamic-datastore` module for our convenience.

Likewise, it is expected that a user have configure the tables locally for `datastore-imdb`. This needs to be handled by the developer.

**Pull request closed without merging**
